[package]
name = "batimg"
version = "0.0.1"
edition = "2018"

[dependencies]
# Local
batimg-core = { path = "../core" }
# Extern
clap = { version = "3.0.5", features = ["derive"] }
terminal_size = "0.1.17"
ffmpeg-next = "4.4.0"
image = "0.23.14"
rodio = "0.14.0"
ctrlc = "3.2.1"

