[package]
name = "batimg"
version = "1.2.1"
edition = "2018"

[dependencies]
videostream = { path = "lib/videostream" }
ffmpeg = {git = "https://github.com/meh/rust-ffmpeg"}
terminal_size = "0.1.17"
clap = "3.0.0-rc.8"
image = "0.23.14"
rodio = "0.14.0"
rayon = "1.5.1"
ctrlc = "3.2.1"

