[package]
name = "adplay"
version = "1.1.0"
edition = "2018"

[dependencies]
rodio = {git="https://github.com/RustAudio/rodio"}
terminal_size = "0.1.17"
clap = "3.0.0-beta.5"
image = "0.23.14"
ctrlc = "3.2.1"

